# Generated by Django 5.0.3 on 2024-03-31 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reg_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fn', models.CharField(max_length=25)),
                ('mb', models.IntegerField()),
                ('gn', models.CharField(max_length=10)),
                ('st', models.CharField(max_length=25)),
                ('em', models.EmailField(max_length=254)),
                ('ps', models.CharField(max_length=25)),
                ('cps', models.CharField(max_length=25)),
            ],
        ),
    ]
