# Generated by Django 4.2.7 on 2024-04-02 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeaveApp', '0002_leave_req'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave_req',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
