# Generated by Django 4.2.7 on 2024-04-04 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LeaveApp', '0004_leave_req_basic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave_req',
            name='basic',
        ),
    ]
