# Generated by Django 4.2.7 on 2024-04-27 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeaveApp', '0005_remove_leave_req_basic'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave_req',
            name='st',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
