# Generated by Django 4.2.7 on 2024-04-30 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeaveApp', '0008_leave_req_tk'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave_req',
            name='cmn',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='leave_req',
            name='csn',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leave_req',
            name='mtn',
            field=models.IntegerField(default=180),
        ),
        migrations.AddField(
            model_name='leave_req',
            name='ptn',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='leave_req',
            name='tot',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leave_req',
            name='vtn',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
