# Generated by Django 4.2.7 on 2024-04-30 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LeaveApp', '0009_leave_req_cmn_leave_req_csn_leave_req_mtn_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave_req',
            name='cmn',
        ),
        migrations.RemoveField(
            model_name='leave_req',
            name='csn',
        ),
        migrations.RemoveField(
            model_name='leave_req',
            name='mtn',
        ),
        migrations.RemoveField(
            model_name='leave_req',
            name='ptn',
        ),
        migrations.RemoveField(
            model_name='leave_req',
            name='tk',
        ),
        migrations.RemoveField(
            model_name='leave_req',
            name='tot',
        ),
        migrations.RemoveField(
            model_name='leave_req',
            name='vtn',
        ),
    ]
