# Generated by Django 4.2.7 on 2024-04-30 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeaveApp', '0010_remove_leave_req_cmn_remove_leave_req_csn_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='leave_reg_lwa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=25)),
                ('st', models.CharField(max_length=25)),
                ('lt', models.CharField(max_length=25)),
                ('lop', models.IntegerField()),
                ('md', models.FileField(upload_to='medical')),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('rs', models.TextField()),
                ('rd', models.IntegerField()),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
    ]
