# Generated by Django 4.2.7 on 2024-04-01 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0002_remove_leaveinfo_st'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usr', models.CharField(max_length=25)),
                ('psw', models.CharField(max_length=25)),
            ],
        ),
    ]
