# Generated by Django 4.2.7 on 2024-04-05 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0004_payroll_tbl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll_tbl',
            name='end',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='payroll_tbl',
            name='start',
            field=models.CharField(max_length=25),
        ),
    ]
