# Generated by Django 4.2.7 on 2024-04-22 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0005_alter_payroll_tbl_end_alter_payroll_tbl_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll_tbl',
            name='net',
            field=models.FloatField(),
        ),
    ]
