# Generated by Django 4.2.7 on 2024-04-27 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0006_alter_payroll_tbl_net'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaveinfo',
            old_name='sl',
            new_name='cl',
        ),
        migrations.AddField(
            model_name='leaveinfo',
            name='hp',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
