# Generated by Django 4.2.7 on 2024-04-27 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0007_rename_sl_leaveinfo_cl_leaveinfo_hp'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveinfo',
            name='sl',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
