# Generated by Django 4.2.7 on 2024-04-27 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0008_leaveinfo_sl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll_tbl',
            name='wd',
        ),
    ]
