# Generated by Django 4.2.7 on 2024-04-27 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0009_remove_payroll_tbl_wd'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll_tbl',
            name='rm',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
