# Generated by Django 4.2.7 on 2024-04-29 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0010_payroll_tbl_rm'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll_tbl',
            name='al',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payroll_tbl',
            name='st',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
