# Generated by Django 4.2.7 on 2024-04-29 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0012_assign_tbl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaveinfo',
            name='hp',
        ),
    ]
