# Generated by Django 4.2.7 on 2024-04-30 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0014_leaveinfo_sn_leaveinfo_st'),
    ]

    operations = [
        migrations.CreateModel(
            name='lwa_payroll_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=25)),
                ('lt', models.CharField(max_length=25)),
                ('st', models.CharField(max_length=25)),
                ('start', models.CharField(max_length=25)),
                ('end', models.CharField(max_length=25)),
                ('basic', models.IntegerField()),
                ('lop', models.IntegerField()),
                ('net', models.FloatField()),
            ],
        ),
    ]
